# Generated by Django 5.2 on 2025-04-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_customuser_alter_chaishop_owner_delete_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
